### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by johnatasjmo** [drush-ops/config-extra#15]
After installation, I receive an error on running:

`The drush command 'config-merge @dev' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new         [error]
extensions.`

After running $drush cache-clear drush it gets the same error. I am running the command on Mac 10.11.6 and from drupalvm. Doesnt work

**Comment by gravypower** [comment]
see https://github.com/drush-ops/config-extra/pull/14 this seems to have worked for me.
